### ISSUE TITLE
运行模式

### ISSUE THREAD

**Issue by selfInnovator** [YWL0720/YOLO_ORB_SLAM3_with_pointcloud_map#3]
请问，这个工作对于orbslam3的各种模式都可以运行吗，单目、双目、rgbd还有加imu都适配吗

**Comment by YWL0720** [comment]
您好，目前只适用于rgbd模式。这也只是之前在学习时写的版本，后续也一致没完善。如果您感兴趣的话，可以添加一个点云降采样的过程，防止运行时内存占用过大。单双目以及IMU模式接口的更改也比较简单，您可以自行尝试
