### ISSUE TITLE
导航问题

### ISSUE THREAD

**Issue by 1574019603** [YWL0720/YOLO_ORB_SLAM3_with_pointcloud_map#5]
作者你好，我是一名SLAM小白，首先感谢你的代码给了我相当大的提示；其次我想问一下你的这个项目所构建的地图是可以直接用于导航的稠密点云图是吗

**Comment by YWL0720** [comment]
你好。很高兴能给你带来帮助，但是这个版本只是之前工作的一个小demo，还有一些问题，后续一直没有完善，如果最近有时间的话我会更新一下。因为我不是做导航这一块的，不太清楚你具体的需求，可能导航的话需要八叉树地图更多一些？这里构建的是关键帧的稠密点云，应该可以比较方便的转换成你需要的格式。
